openapi: 3.0.0
info:
  title: Simple API
  description: Example of Swagger API
  version: 1.0.0
paths:
  /books:
    get:
      summary: Get list of books
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    author:
                      type: string